name: Deploy Flutter Web App to GitHub Pages
 
on:
  push:
    branches:
      - main  # Replace with your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history so the deployment can proceed

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'  # Use the appropriate version

    - name: Install dependencies
      run: flutter pub get

    - name: Build Flutter web app
      run: flutter build web --release

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/web  # Ensure this is set correctly to the output directory
        keep_files: false  # Removes old files from gh-pages branch, ensuring a clean deploy
        # cname: 'yourdomain.com'  # Uncomment if using a custom domain

    - name: Post deployment message
      run: echo "Flutter web app deployed to GitHub Pages!"

